SecDebugLog /var/log/nginx/modsec_debug.log
SecDebugLogLevel 3

# Change to On when 100% ready to prod / Modify to take env value
SecRuleEngine On
SecRequestBodyAccess On
# SecRule REQUEST_URI "^/" "id:999998,phase:1,block,log,msg:'MODSEC HTTP TEST',severity:2"

# Log settings
SecAuditEngine RelevantOnly
SecAuditLog /var/log/nginx/modsec_audit.log
SecAuditLogParts ABIJDEFHZ

# Includes files as crs and custom rules

Include /etc/modsecurity/rules/*.conf

Include /etc/modsecurity/crs/crs-setup.conf

Include /usr/share/modsecurity-crs/rules/*.conf

