
# ModSecurity configuration file for Nginx
 # If user received 403 error too frequently, it can be caused by ModSecurity rules.
 # In that case, we can disable Modsecurity by modifying SecRuleEngine On to DetectionOnly
 # to only get logs without blocking requests, or Off.
 # Once it is done, we need to check logs and modify rules accordingly.
SecRuleEngine DetectionOnly # Change to On when 100% ready to prod / Modify to take env value
SecRequestBodyAccess On

# Log settings
SecAuditEngine RelevantOnly
SecAuditLog /var/log/nginx/modsec_audit.log
SecAuditLogParts ABIJDEFHZ

 # This is the differents configurations rules for ModSecurity
Include /etc/modsecurity/crs/crs-setup.conf
Include /etc/modsecurity/crs/rules/*.conf