services:
  nginx:
    environment:
      WEB_PORT: 5173
    image: ft_transcendence-nginx:dev

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    image: ft_transcendence-web:dev
    hostname: web
    volumes:
      - ./web:/app
      - /app/node_modules
    expose:
      - "5173"
    healthcheck:
      test: [ "CMD", "curl", "-i", "http://localhost:5173" ]
      interval: 5s
      timeout: 3s
      retries: 3

  game_api:
    build:
      context: ./game_api
      dockerfile: Dockerfile.dev
    image: ft_transcendence-game_api:dev
    volumes:
      - ./game_api/src:/app/src
