services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ft_transcendence-nginx:prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/data/logs:/var/log/nginx
      - ./nginx/data/certs:/etc/nginx/certs
      - vault-secrets:/secrets:ro
      - ./shared:/scripts:ro
      - modsec-data:/var/cache/modsecurity
    depends_on:
      sqlite_api:
        condition: service_healthy
      web:
        condition: service_healthy
    networks:
      - frontend
      - backend

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ft_transcendence-web:prod
    hostname: web
    depends_on:
      vault_agent:
        condition: service_healthy
    volumes:
      - vault-secrets:/secrets
      - ./shared:/scripts:ro
    expose:
      - "80"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 3


  sqlite_api:
    build:
      context: ./sqlite_api
      dockerfile: Dockerfile
    image: ft_transcendence-sqlite_api:prod
    container_name: sqlite_api
    expose:
      - "3000"
    volumes:
      - ./sqlite_api/data:/app/data
      - vault-secrets:/secrets:ro
      - ./shared:/scripts:ro
    depends_on:
      - vault_agent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - backend

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    tmpfs:
      - /run:rw,noexec,nosuid,nodev
      - /tmp:rw,noexec,nosuid,nodev
    environment:
      VAULT_ADDR: https://vault:8200
      VAULT_CACERT: /vault/certs/vault.cert
    volumes:
      - vault_data:/vault/data
      - ./data/file:/vault/file
      - ./vault/certs:/vault/certs
      - ./vault/config:/vault/config
      - ./secrets:/run/secrets:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -skf https://vault:8200/v1/sys/health | jq -e '.sealed==false' >/dev/null"]
      interval: 3s
      timeout: 2s
      retries: 40

  vault_agent:
    image: hashicorp/vault:1.20
    container_name: vault-agent
    command: ["/vault/vault-agent-entrypoint.sh"]
    cap_add:
      - IPC_LOCK
    depends_on:
      vault:
        condition: service_healthy
    volumes:
      - ./data/file:/vault/file:ro
      - vault-secrets:/secrets
      - ./vault:/vault
    environment:
      - VAULT_ADDR=https://vault:8200
      - VAULT_CACERT=/vault/certs/vault.cert
    healthcheck:
      test: ["CMD-SHELL", "[ -s /secrets/sqlite_api/app.env ]  && [ -s /secrets/ws_server/app.env ] && [ -s /secrets/web/app.env ]"]
      interval: 2s
      timeout: 2s
      retries: 20

  ws_server:
    build:
      context: ./ws_server
      dockerfile: Dockerfile
    image: ft_transcendence-ws_server:prod
    container_name: ws_server
    expose:
      - "3000"
    volumes:
      - vault-secrets:/secrets:ro
      - ./shared:/scripts:ro
    restart: unless-stopped
    depends_on:
      vault_agent:
        condition: service_healthy
    extra_hosts:
      - "api.dev.local:host-gateway"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "frontend"
      com.docker.network.bridge.enable_icc: "true"
    ipam:
      config:
        - subnet: "172.30.0.0/16" # We preset to keep a consistent network for firewall rules
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "backend"
      com.docker.network.bridge.enable_icc: "true"

volumes:
  vault_data:
  vault-secrets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  modsec-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

