services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ft_transcendence-nginx:prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      API_PORT: ${API_PORT}
      MODSEC_MODE: ${MODSEC_MODE}
      WEB_PORT: 80
      VAULT_PORT: ${VAULT_PORT}
    volumes:
      - ./nginx/data/logs:/var/log/nginx
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      sqlite_api:
        condition: service_healthy
      web:
        condition: service_healthy
    networks:
      - frontend
      - backend

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ft_transcendence-web:prod
    hostname: web
    environment:
      VITE_DOMAIN: ${DOMAIN_NAME}
      VITE_API_URL: api.${DOMAIN_NAME}
      VITE_PONG_WS_URL: pong.ws.${DOMAIN_NAME}
    expose:
      - "80"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   hostname: api
  #   environment:
  #     API_PORT: ${API_PORT}
  #   networks:
  #     - backend
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:${API_PORT}/ping"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3


  sqlite_api:
    build:
      context: ./sqlite_api
      dockerfile: Dockerfile
    container_name: sqlite_api
    expose:
      - "3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PORT: ${DATABASE_PORT}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
    volumes:
      - ./sqlite_api/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - backend

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    tmpfs:
      - /run:rw,noexec,nosuid,nodev
      - /tmp:rw,noexec,nosuid,nodev
    environment:
      VAULT_ADDR: https://vault:8200 # TODO: Change 8200 by an env variable
      # VAULT_CACERT: "/vault/certs/vault.crt" #TODO: Check certs
    volumes:
      - ./data/file:/vault/file
      - ./vault/config:/vault/config
      - ./vault/certs:/vault/certs
      - vault_data:/vault/data
      - ./secrets:/run/secrets:ro
      - ./nginx/data/certs:/vault/certs

  ws_server:
    build:
      context: ./ws_server
      dockerfile: Dockerfile
    container_name: ws_server
    expose:
      - "3000"
    environment:
      - API_URL=api.${DOMAIN_NAME}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    extra_hosts:
      - "api.dev.local:host-gateway"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "frontend"
      com.docker.network.bridge.enable_icc: "true"
    ipam:
      config:
        - subnet: "172.30.0.0/16" # We preset to keep a consistent network for firewall rules
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "backend"
      com.docker.network.bridge.enable_icc: "true"

volumes:
  vault_data:
