services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ft_transcendence-nginx:prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WEB_PORT: 80
    volumes:
      - ./nginx/data/logs:/var/log/nginx
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      api:
        condition: service_healthy
      web:
        condition: service_healthy
    networks:
      - frontend
      - backend

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ft_transcendence-web:prod
    hostname: web
    environment:
      VITE_API_URL: api.${DOMAIN_NAME}
      VITE_GAME_API_URL: game.api.${DOMAIN_NAME}
      VITE_PONG_WS_URL: pong.ws.${DOMAIN_NAME}
    expose:
      - "80"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 3

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    hostname: api
    expose:
      - 3000
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  sqlite_api:
    build:
      context: ./sqlite_api
      dockerfile: Dockerfile
    container_name: sqlite_api
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./sqlite_api/src:/app/src
      - ./sqlite_api/data:/app/data
      - ./sqlite_api/package.json:/app/package.json
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - backend

  game_api:
    build:
      context: ./game_api
      dockerfile: Dockerfile
    container_name: game_api
    expose:
      - "3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PORT: ${DATABASE_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend

  ws_server:
    build:
      context: ./ws_server
      dockerfile: Dockerfile
    container_name: ws_server
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - backend

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "frontend"
      com.docker.network.bridge.enable_icc: "true"
    ipam:
      config:
        - subnet: "172.30.0.0/16" # We preset to keep a consistent network for firewall rules
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "backend"
      com.docker.network.bridge.enable_icc: "true"
