import fs from "fs";
import dotenv from "dotenv";

dotenv.config();

const vars = {
    DOMAIN: `https://${process.env.VITE_DOMAIN || "localhost"}`,
    API_URL: `https://${process.env.VITE_API_URL || "localhost/api"}`,
    PONG_WS_URL: `https://${process.env.VITE_PONG_WS_URL || "localhost/ws"}`,
    NODE_ENV: process.env.VITE_NODE_ENV || "development",
};

const content = `// WARNING Auto-generated by scripts/inject-env.js — do not edit manually
export const env = ${JSON.stringify(vars, null, 2)} as const;
`;

fs.writeFileSync("src/env.ts", content);
console.log("Environment variables injected into src/env.ts");