#crs-setup.conf


SecAction "id:900001,phase:1,nolog,pass,\
  setvar:tx.crs_setup_version=1,\
  setvar:tx.allowed_methods=GET POST OPTIONS HEAD,\
  setvar:tx.paranoia_level=1,\
  setvar:tx.request_body_access=On,\
  setvar:tx.response_body_access=Off"

#Will add that, therefor i need to test modsecurity custom rules in case this is not enough
# setvar:tx.allowed_methods=GET POST OPTIONS HEAD
