# 01-whitelist-extension.conf
SecRule REQUEST_URI "@rx \.(?!html|css|js|mjs|ts|tsx|webp|png|jpe?g|gif|svg|ico|woff2?|ttf|map|json|webmanifest|wasm)([a-zA-Z0-9]+)(?:\?|$)" \
    "id:1000002, \
    phase:1, \
    deny, \
    status:403, \
    log,msg:'Disallowed file extension'"