user www-data;
worker_processes auto;
pid /run/nginx.pid;
load_module modules/ngx_http_modsecurity_module.so;



events {
	worker_connections 1024;
}

http {
	ssl_protocols TLSv1.2 TLSv1.3;
	include       mime.types;

	index index.html index.htm index.php;

	client_body_buffer_size 128k;
	client_max_body_size 12m;

	map $request_method $allow_header {
		"~^(GET|POST|OPTIONS|HEAD)$" "";
		default "GET, POST, OPTIONS, HEAD";
	}
	add_header Allow $allow_header always;

	# Redirect HTTP to HTTPS
	server {
		listen 80;
		listen [::]:80;
		server_name DOMAIN_NAME;

		error_page 403 = @handle_405;

		location / {
			limit_except GET POST OPTIONS HEAD {
				deny all;
			}
			return 301 https://$host$request_uri;
		}
		location @handle_405 {
			return 405;
		}
	}


	# Main server block
	server {
		ssl_certificate /etc/nginx/certs/fullchain.pem_DOMAIN_NAME;
		ssl_certificate_key /etc/nginx/certs/privkey.pem_DOMAIN_NAME;

		listen 443 ssl;
		listen [::]:443 ssl;
		server_name DOMAIN_NAME localhost;

		# Enable ModSecurity
		# modsecurity on;
		# modsecurity_rules_file /etc/modsecurity/modsecurity.conf;

		root /usr/share/nginx/html;

		location / {
			# autoindex on;
			try_files $uri $uri/ /index.html =404;
		}
	}

	# API server block
	server {
		ssl_certificate /etc/nginx/certs/fullchain.pem_api.DOMAIN_NAME;
		ssl_certificate_key /etc/nginx/certs/privkey.pem_api.DOMAIN_NAME;

		listen 443 ssl;
		listen [::]:443 ssl;
		server_name api.DOMAIN_NAME api.localhost;

		location / {
			proxy_pass http://api:API_PORT;
			proxy_set_header X-Proxy-Origin nginx;
		}
	}
}