user www-data;
worker_processes auto;
pid /run/nginx.pid;
load_module modules/ngx_http_modsecurity_module.so;



events {
	worker_connections 1024;
}

http {
    ssl_protocols TLSv1.2 TLSv1.3;
    include       mime.types;
  
  # Basic protections rules
  client_body_buffer_size 128k;
	client_max_body_size 12m;

  #Map use to avoid wrong Header packet
	map $request_method $allow_header {
		"~^(GET|POST|OPTIONS|HEAD)$" "";
		default "GET, POST, OPTIONS, HEAD";
	}
	add_header Allow $allow_header always;

    # Redirect HTTP to HTTPS
    server {
        listen 80;
        listen [::]:80;
        server_name DOMAIN_NAME;
    
    		error_page 403 = @handle_405;
    
    		location / {
			    limit_except GET POST OPTIONS HEAD {
				    deny all;
			    }
		    }
    
		   location @handle_405 {
			    return 405;
		    }
        return 301 https://$host$request_uri;
    }

    # Main server block
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name DOMAIN_NAME;

        ssl_certificate /etc/nginx/certs/fullchain.pem_DOMAIN_NAME;
        ssl_certificate_key /etc/nginx/certs/privkey.pem_DOMAIN_NAME;
    
        # Enable ModSecurity
		    # modsecurity on;
		    # modsecurity_rules_file /etc/modsecurity/modsecurity.conf;

        location / {
      #Need to check if still useful with proxy system
      #  		try_files $uri $uri/ /index.html =404; 
            proxy_pass http://web:80;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # API server block
    server {
        ssl_certificate /etc/nginx/certs/fullchain.pem_DOMAIN_NAME;
        ssl_certificate_key /etc/nginx/certs/privkey.pem_DOMAIN_NAME;

        listen 443 ssl;
        listen [::]:443 ssl;
        server_name api.DOMAIN_NAME;

        location / {
            proxy_pass http://api:API_PORT;
            proxy_set_header X-Proxy-Origin nginx;
        }
    }
}
