# web/Dockerfile.dev
FROM node:20

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY vite.config.ts ./
COPY tailwind.config.js ./
COPY postcss.config.js ./

RUN npm install

CMD ["npm", "run", "dev"]