server {
	listen 80;
	server_name localhost;

	root /usr/share/nginx/html;
	index index.html;

	location / {
		try_files $uri $uri/ /index.html;
	}

	location = /config.js {
		add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate" always;
		add_header Pragma "no-cache" always;
		add_header Expires "0" always;
		try_files /config.js =404;
	}
}